name: expand_widget
description: Ability to easily expand and retract a widget collection or text.
version: 0.2.0+2
author: Jesus Rodriguez <jesusrope98@outlook.com>
homepage: https://github.com/jesusrp98/expand_widget

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter